### PR TITLE
add volume section in docker-compose.yml

### PR DESCRIPTION
**Pull request by MrMarioMichel**
add volume section as mentioned at https://github.com/immauss/openvas/pull/8#pullrequestreview-482454079

grafik

### CODE REVIEW

**Comment by immauss** [comment]
Sorry it too so long to merge this. I've been focused on getting 20.08 stable.
Can you verify the compose yml still works. I've not done much with compose ...

**Comment by MrMarioMichel** [comment]
Also, not a pro but with a clean reinstall (Fully prune old volumes and container). Yes, works all fine. Thank you !!! I will keep you updated for any changes in behavior.

**Comment by MrMarioMichel** [comment]
Hmmm something is weird some scans are randomly stopping. Scans against my own machine is working, but I can resolve and ping any host outside the network so not a connection issue. Still scans finish in seconds or take ages and are randomly stopping.

grafik

Can you check if this also happens at the bare metal installation?

Also try out docker-compose it's even simpler than docker and tell me your results.

**Comment by immauss** [comment]
I actually have this running in a production environment with scheduled scans across multiple network boundaries and no issues. Can you give me any more details about your setup that is failing?

docker-compose is great for setting up pre configured environments. It’s one of those pieces that I know I should get to know better, but at the moment, I have everything written in shell scripts… and it works for me.
:)


-Scott


Scott Knauss
scott@immauss.com
Certified Ethical Hacker
Certified Hacking Forensic Investigator, CISSP, RHCE
Immauss Technology Solutions
ITS
It's about solutions
https://www.immauss.com

**Comment by MrMarioMichel** [comment]
FYI: With the latest docker image all works fine with clean install. Thanks!

**Pull request merged**
